# Generated by Django 2.0.2 on 2018-03-02 13:04

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demo_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date_request', models.DateTimeField(verbose_name='booking date requested')),
                ('number_attending', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
                ('date_time_recieved', models.DateTimeField(auto_now_add=True, verbose_name='date & time booked')),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40, validators=[django.core.validators.EmailValidator])),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('date_request', models.DateTimeField(verbose_name='booking date requested')),
                ('time_request', models.TimeField(verbose_name='booking time requested')),
                ('number_attending', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
                ('date_time_recieved', models.DateTimeField(auto_now_add=True, verbose_name='date & time booked')),
            ],
        ),
    ]
