# Generated by Django 2.0.2 on 2018-03-02 03:11

from django.db import migrations, models
import events.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('date_request', models.DateTimeField(verbose_name='booking date requested')),
                ('time_request', models.TimeField(verbose_name='booking time requested')),
                ('number_attending', events.models.IntegerRangeField()),
                ('date_time_recieved', models.DateTimeField(auto_now_add=True, verbose_name='date & time booked')),
            ],
        ),
    ]
