# Generated by Django 2.0.2 on 2018-03-02 11:49

import django.core.validators
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180302_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=40, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='number_attending',
            field=events.models.IntegerRangeField(),
        ),
    ]
