# Generated by Django 2.0.2 on 2018-03-06 22:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180306_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo_form',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 13, 22, 26, 49, 667251, tzinfo=utc), verbose_name='booking date requested'),
        ),
        migrations.AlterField(
            model_name='demo_form',
            name='name',
            field=models.CharField(default='Aaliyah', max_length=40),
        ),
    ]
