# Generated by Django 2.0.2 on 2018-03-07 01:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20180306_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo_form',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 1, 11, 26, 481390, tzinfo=utc), verbose_name='booking date requested'),
        ),
    ]
