# Generated by Django 2.0.2 on 2018-03-07 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20180307_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo_form',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 13, 17, 24, 778503, tzinfo=utc), verbose_name='booking date requested'),
        ),
    ]
