# Generated by Django 2.0.2 on 2018-03-07 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20180307_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo_form',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 18, 18, 12, 228234, tzinfo=utc), verbose_name='booking date requested'),
        ),
    ]
