# Generated by Django 2.0.2 on 2018-03-07 22:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20180307_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo_form',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 22, 26, 12, 11853, tzinfo=utc), verbose_name='booking date requested'),
        ),
    ]
