# Generated by Django 2.0.2 on 2018-03-08 01:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20180307_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo_form',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 15, 1, 13, 21, 522413, tzinfo=utc), verbose_name='booking date requested'),
        ),
    ]
