# Generated by Django 2.0.2 on 2018-03-09 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_auto_20180309_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo_form',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 16, 12, 15, 31, 747465, tzinfo=utc), verbose_name='booking date requested'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='school',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
