# Generated by Django 2.0.2 on 2018-03-09 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_auto_20180309_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo_form',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 16, 13, 25, 39, 717109, tzinfo=utc), verbose_name='booking date requested'),
        ),
    ]
