# Generated by Django 2.0.2 on 2018-03-09 13:42

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc
import events.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_auto_20180309_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date_time_received', events.models.AutoDateTimeField(default=django.utils.timezone.now, verbose_name='booked on')),
                ('email', models.CharField(max_length=40, validators=[django.core.validators.EmailValidator])),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('date_request', models.DateField(verbose_name='date requested')),
                ('time_request', models.TimeField(verbose_name='time requested')),
                ('number_attending', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
                ('school', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='registration',
        ),
        migrations.AlterField(
            model_name='demo_form',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 16, 13, 42, 7, 423502, tzinfo=utc), verbose_name='booking date requested'),
        ),
    ]
