# Generated by Django 2.0.2 on 2018-03-09 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_auto_20180309_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingrequest',
            options={'verbose_name': 'visitor registration', 'verbose_name_plural': 'visitor registrations'},
        ),
        migrations.AlterField(
            model_name='demo_form',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 16, 13, 49, 57, 49309, tzinfo=utc), verbose_name='booking date requested'),
        ),
    ]
