# Generated by Django 2.0.2 on 2018-03-09 14:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_auto_20180309_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='date_request',
            field=models.DateField(default=datetime.date(2018, 3, 16), verbose_name='date requested'),
        ),
        migrations.AlterField(
            model_name='demo_form',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 16, 14, 8, 6, 852178, tzinfo=utc), verbose_name='booking date requested'),
        ),
    ]
