# Generated by Django 2.0.2 on 2018-03-09 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0065_auto_20180309_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo_form',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 16, 15, 6, 3, 550550, tzinfo=utc), verbose_name='booking date requested'),
        ),
    ]
