# Generated by Django 2.0.2 on 2018-03-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0073_auto_20180309_1110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo_form',
        ),
    ]
