# Generated by Django 2.0.2 on 2018-03-09 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0074_delete_demo_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='date_request',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='time_request',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='date_time_request',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date requested'),
        ),
    ]
