# Generated by Django 2.0.2 on 2018-03-11 17:31

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0076_auto_20180309_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='time_request',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='arrival_time',
            field=models.TimeField(default=events.models.current_hour, verbose_name='arrival time'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='departure_time',
            field=models.TimeField(default=events.models.current_hour, verbose_name='departure time'),
        ),
    ]
