# Generated by Django 2.0.2 on 2018-03-11 18:49

from django.db import migrations, models
import events.models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0077_auto_20180311_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='departure_time',
            field=models.TimeField(default=functools.partial(events.models.current_hour, *(), **{'addhours': 1}), verbose_name='departure time'),
        ),
    ]
