# Generated by Django 2.0.2 on 2018-03-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0078_auto_20180311_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='arrival_time',
            field=models.TimeField(verbose_name='arrival time'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='departure_time',
            field=models.TimeField(verbose_name='departure time'),
        ),
    ]
