# Generated by Django 2.0.2 on 2018-03-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0079_auto_20180311_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='school',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
