# Generated by Django 2.0.2 on 2018-03-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0080_auto_20180311_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='date_request',
            field=models.DateField(verbose_name='date requested'),
        ),
    ]
