import time
import unittest

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from seleniumrequests import Firefox

class FunctionalTest(unittest.TestCase):

    def setUp(self):
        print(". . . s e t U p")
        self.browser = webdriver.Firefox()

    def tearDown(self):
        print(". . . t e a r D o w n")
        self.browser.quit()

    def test_selenium_webdriver(self):
        print(". . . test_selenium_webdriver: ", end="")
        self.browser.get('http://localhost:8000')
        print("OK")

    def test_can_register_event(self):
        print(". . . test_can_register_event... ")
        print(". . . > the user can get to the add page")
        self.browser.get('http://localhost:8000/login/')
        name = self.browser.find_element_by_css_selector('input#id_username')
        name.clear()
        name.send_keys("pinotnoir")
        name = self.browser.find_element_by_css_selector('input#id_password')
        name.clear()
        name.send_keys("pinotnoir")
        button = self.browser.find_element_by_id('login_button')
        button.click()
        time.sleep(1)
        self.browser.get('http://localhost:8000/events/new/')

        print(". . . > the user can see the form")
        form = self.browser.find_element_by_tag_name('form')

        # FORM FIELDS TESTS
        print(". . . > the user can see the name field")
        self.browser.find_element_by_id("id_name")
        print(". . . > .................... email field")
        self.browser.find_element_by_id("id_email")
        print(". . . > .................... telephone field")
        self.browser.find_element_by_id("id_telephone")
        print(". . . > .................... date request field")
        self.browser.find_element_by_id("id_date_request")
        print(". . . > .................... arrival time field")
        self.browser.find_element_by_id("id_arrival_time_hour")
        print(". . . > .................... departure time field")
        self.browser.find_element_by_id("id_departure_time_hour")
        # print(". . . > .................... number_attending field")
        self.browser.find_element_by_id("id_number_attending")
        print(". . . > .................... school field")
        self.browser.find_element_by_id("id_school")

        name = self.browser.find_element_by_css_selector('input#id_name')
        name.clear()
        # time.sleep(.5)
        name.send_keys("Danny Burrito")
        name = self.browser.find_element_by_css_selector('input#id_email')
        name.clear()
        # time.sleep(.5)
        name.send_keys("person@webbersitorino.com")
        name = self.browser.find_element_by_css_selector('input#id_telephone')
        name.clear()
        # time.sleep(.5)
        name.send_keys("6463012333")
        name = self.browser.find_element_by_css_selector('select#id_arrival_time_hour')
        name.send_keys(Keys.DOWN)
        name = self.browser.find_element_by_css_selector('select#id_arrival_time_minute')
        name.send_keys(Keys.DOWN)
        name = self.browser.find_element_by_css_selector('select#id_arrival_time_meridiem')
        name.send_keys(Keys.UP)
        # arrival: 10:30 a.m.
        name = self.browser.find_element_by_css_selector('select#id_departure_time_hour')
        name.send_keys(Keys.DOWN)
        name.send_keys(Keys.DOWN)
        name.send_keys(Keys.DOWN)
        name = self.browser.find_element_by_css_selector('select#id_departure_time_meridiem')
        name.send_keys(Keys.DOWN)
        # departure: 12:00 p.m.
        name = self.browser.find_element_by_css_selector('input#id_number_attending')
        name.clear()
        name.send_keys("20")
        name = self.browser.find_element_by_css_selector('input#id_school')
        name.clear()
        name.send_keys("Schoolversity")
        name.submit()
        print(". . . test_can_register_event: OK")

    def test_can_edit_form(self):
        print(". . . test_can_edit_form... ")
        print(". . . > the user can get to the add page")
        self.browser.get('http://localhost:8000/login/')
        name = self.browser.find_element_by_css_selector('input#id_username')
        name.clear()
        name.send_keys("pinotnoir")
        name = self.browser.find_element_by_css_selector('input#id_password')
        name.clear()
        name.send_keys("pinotnoir")
        button = self.browser.find_element_by_id('login_button')
        button.click()
        time.sleep(1)
        self.browser.get('http://localhost:8000/events/new/')
        # ADD INFORMATION
        name = self.browser.find_element_by_css_selector('input#id_name')
        name.clear()
        name.send_keys("Danny Burrito")
        name = self.browser.find_element_by_css_selector('input#id_email')
        name.clear()
        name.send_keys("person@webbersitorino.com")
        name = self.browser.find_element_by_css_selector('input#id_telephone')
        name.clear()
        name.send_keys("6463012333")
        name = self.browser.find_element_by_css_selector('select#id_arrival_time_hour')
        name.send_keys(Keys.DOWN)
        name = self.browser.find_element_by_css_selector('select#id_arrival_time_minute')
        name.send_keys(Keys.DOWN)
        name = self.browser.find_element_by_css_selector('select#id_arrival_time_meridiem')
        name.send_keys(Keys.UP)
        name = self.browser.find_element_by_css_selector('select#id_departure_time_hour')
        name.send_keys(Keys.DOWN)
        name.send_keys(Keys.DOWN)
        name.send_keys(Keys.DOWN)
        name = self.browser.find_element_by_css_selector('select#id_departure_time_meridiem')
        name.send_keys(Keys.DOWN)
        name = self.browser.find_element_by_css_selector('input#id_number_attending')
        name.clear()
        name.send_keys("20")
        name = self.browser.find_element_by_css_selector('input#id_school')
        name.clear()
        name.send_keys("Schoolversity")
        name.submit()
        # go to edit page
        time.sleep(1)
        button = self.browser.find_element_by_id('edit_button')
        button.click()
        # ADD INFORMATION (again)
        name = self.browser.find_element_by_css_selector('input#id_name')
        name.clear()
        name.send_keys("Danny Burrito")
        name = self.browser.find_element_by_css_selector('input#id_email')
        name.clear()
        name.send_keys("person@webbersitorino.com")
        name = self.browser.find_element_by_css_selector('input#id_telephone')
        name.clear()
        name.send_keys("6463012333")
        name = self.browser.find_element_by_css_selector('select#id_arrival_time_hour')
        name.send_keys(Keys.DOWN)
        name = self.browser.find_element_by_css_selector('select#id_arrival_time_minute')
        name.send_keys(Keys.DOWN)
        name = self.browser.find_element_by_css_selector('select#id_arrival_time_meridiem')
        name.send_keys(Keys.UP)
        # arrival: 10:30 a.m.
        name = self.browser.find_element_by_css_selector('select#id_departure_time_hour')
        name.send_keys(Keys.DOWN)
        name.send_keys(Keys.DOWN)
        name.send_keys(Keys.DOWN)
        name = self.browser.find_element_by_css_selector('select#id_departure_time_meridiem')
        name.send_keys(Keys.DOWN)
        # departure: 12:00 p.m.
        name = self.browser.find_element_by_css_selector('input#id_number_attending')
        name.clear()
        name.send_keys("20")
        name = self.browser.find_element_by_css_selector('input#id_school')
        name.clear()
        name.send_keys("Schoolversity")
        name.submit()
        print(". . . test_can_edit_form: OK")

    def test_can_see_post_list(self):
        print(". . . test_can_see_post_list... ")
        self.browser.get('http://localhost:8000/login/')
        name = self.browser.find_element_by_css_selector('input#id_username')
        name.clear()
        name.send_keys("pinotnoir")
        name = self.browser.find_element_by_css_selector('input#id_password')
        name.clear()
        name.send_keys("pinotnoir")
        button = self.browser.find_element_by_id('login_button')
        button.click()
        time.sleep(1)
        # go to new form
        self.browser.get('http://localhost:8000/events/new/')
        # submit information
        name = self.browser.find_element_by_css_selector('input#id_name')
        name.clear()
        name.send_keys("Danny Likes PageLists")
        name = self.browser.find_element_by_css_selector('input#id_email')
        name.clear()
        name.send_keys("person@webbersitorino.com")
        name = self.browser.find_element_by_css_selector('input#id_telephone')
        name.clear()
        name.send_keys("6463012333")
        name = self.browser.find_element_by_css_selector('select#id_arrival_time_hour')
        name.send_keys(Keys.DOWN)
        name = self.browser.find_element_by_css_selector('select#id_arrival_time_minute')
        name.send_keys(Keys.DOWN)
        name = self.browser.find_element_by_css_selector('select#id_arrival_time_meridiem')
        name.send_keys(Keys.UP)
        # arrival: 10:30 a.m.
        name = self.browser.find_element_by_css_selector('select#id_departure_time_hour')
        name.send_keys(Keys.DOWN)
        name.send_keys(Keys.DOWN)
        name.send_keys(Keys.DOWN)
        name = self.browser.find_element_by_css_selector('select#id_departure_time_meridiem')
        name.send_keys(Keys.DOWN)
        # departure: 12:00 p.m.
        name = self.browser.find_element_by_css_selector('input#id_number_attending')
        name.clear()
        name.send_keys("20")
        name = self.browser.find_element_by_css_selector('input#id_school')
        name.clear()
        name.send_keys("Schoolversity")
        name.submit()
        # go to event event_list
        self.browser.get('http://localhost:8000/events/all/')
        # see event is there
        html = self.browser.find_element_by_tag_name('tbody').text
        self.assertIn('Danny Likes PageLists', html)
        print(". . . test_can_edit_form: OK")

    def test_can_delete_post(self):
        print(". . . test_can_edit_form... ")
        print(". . . > the user can get to the add page")
        self.browser.get('http://localhost:8000/login/')
        name = self.browser.find_element_by_css_selector('input#id_username')
        name.clear()
        name.send_keys("pinotnoir")
        name = self.browser.find_element_by_css_selector('input#id_password')
        name.clear()
        name.send_keys("pinotnoir")
        button = self.browser.find_element_by_id('login_button')
        button.click()
        time.sleep(1)
        self.browser.get('http://localhost:8000/events/new/')
        # ADD INFORMATION
        name = self.browser.find_element_by_css_selector('input#id_name')
        name.clear()
        name.send_keys("Danny Delete-o")
        name = self.browser.find_element_by_css_selector('input#id_email')
        name.clear()
        name.send_keys("person@webbersitorino.com")
        name = self.browser.find_element_by_css_selector('input#id_telephone')
        name.clear()
        name.send_keys("6463012333")
        name = self.browser.find_element_by_css_selector('select#id_arrival_time_hour')
        name.send_keys(Keys.DOWN)
        name = self.browser.find_element_by_css_selector('select#id_arrival_time_minute')
        name.send_keys(Keys.DOWN)
        name = self.browser.find_element_by_css_selector('select#id_arrival_time_meridiem')
        name.send_keys(Keys.UP)
        name = self.browser.find_element_by_css_selector('select#id_departure_time_hour')
        name.send_keys(Keys.DOWN)
        name.send_keys(Keys.DOWN)
        name.send_keys(Keys.DOWN)
        name = self.browser.find_element_by_css_selector('select#id_departure_time_meridiem')
        name.send_keys(Keys.DOWN)
        name = self.browser.find_element_by_css_selector('input#id_number_attending')
        name.clear()
        name.send_keys("20")
        name = self.browser.find_element_by_css_selector('input#id_school')
        name.clear()
        name.send_keys("Schoolversity")
        name.submit()
        time.sleep(2)
        button = self.browser.find_element_by_id('delete_button')
        button.click()
        time.sleep(1)
        self.browser.get('http://localhost:8000/events/all/')
        time.sleep(1)
        page_source = self.browser.page_source
        self.assertNotIn('Danny Delete-o', page_source)
        print(". . . test_can_edit_form: OK")

    def test_login(self):
        print(". . . test_login: ", end="")
        self.browser.get('http://localhost:8000/login/')
        name = self.browser.find_element_by_css_selector('input#id_username')
        name.clear()
        name.send_keys("pinotnoir")
        name = self.browser.find_element_by_css_selector('input#id_password')
        name.clear()
        name.send_keys("pinotnoir")
        time.sleep(1)
        button = self.browser.find_element_by_id('login_button')
        button.click()
        time.sleep(1)
        page_source = self.browser.page_source
        self.assertIn('Logged in', page_source)
        print("OK")

    def test_logout(self):
        print(". . . test_logout: ", end="")
        self.browser.get('http://localhost:8000/login/')
        name = self.browser.find_element_by_css_selector('input#id_username')
        name.clear()
        name.send_keys("pinotnoir")
        name = self.browser.find_element_by_css_selector('input#id_password')
        name.clear()
        name.send_keys("pinotnoir")
        time.sleep(1)
        button = self.browser.find_element_by_id('login_button')
        button.click()
        time.sleep(1)
        self.browser.get('http://localhost:8000/logout/')
        page_source = self.browser.page_source
        self.assertIn('not logged in', page_source)
        print("OK")

    def test_signup(self):
        print(". . . test_signup: ", end="")
        self.browser.get('http://localhost:8000/login/')
        name = self.browser.find_element_by_css_selector('input#id_username')
        name.clear()
        name.send_keys("pinotnoir")
        name = self.browser.find_element_by_css_selector('input#id_password')
        name.clear()
        name.send_keys("pinotnoir")
        time.sleep(1)
        button = self.browser.find_element_by_id('login_button')
        button.click()
        time.sleep(1)
        self.browser.get('http://localhost:8000/signup/')
        page_source = self.browser.page_source
        self.assertIn('Create', page_source)
        name = self.browser.find_element_by_css_selector('input#id_username')
        name.clear()
        name.send_keys("newdude")
        name = self.browser.find_element_by_css_selector('input#id_password1')
        name.clear()
        name.send_keys("randompass")
        name = self.browser.find_element_by_css_selector('input#id_password2')
        name.clear()
        name.send_keys("randompass")
        self.browser.get('http://localhost:8000/login/')
        # ADD INFORMATION
        name = self.browser.find_element_by_css_selector('input#id_username')
        name.clear()
        name.send_keys('newdude')
        name = self.browser.find_element_by_css_selector('input#id_password')
        name.clear()
        name.send_keys("randompass")
        time.sleep(1)
        button = self.browser.find_element_by_id('login_button')
        button.click()
        time.sleep(1)
        page_source = self.browser.page_source
        self.assertIn('newdude', page_source)
        print("OK")

def suite():
    suite = unittest.TestSuite()
    suite.addTest(FunctionalTest('test_selenium_webdriver'))
    suite.addTest(FunctionalTest('test_login'))
    suite.addTest(FunctionalTest('test_logout'))
    suite.addTest(FunctionalTest('test_signup'))
    suite.addTest(FunctionalTest('test_can_register_event'))
    suite.addTest(FunctionalTest('test_can_edit_form'))
    suite.addTest(FunctionalTest('test_can_see_post_list'))
    suite.addTest(FunctionalTest('test_can_delete_post'))
    return suite

if __name__ == '__main__':
    runner = unittest.TextTestRunner(failfast=True)
    runner.run(suite())
    #unittest.main(warnings='ignore')
